# Generated by Django 4.2.13 on 2024-08-05 14:44

from django.db import migrations, models
import utils.image_upload


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.image_upload.upload_instance_image,
                verbose_name="Постер",
            ),
        ),
    ]
