# Generated by Django 4.2.13 on 2024-08-07 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_episode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="episodes_count",
        ),
    ]
