# Generated by Django 4.2.13 on 2024-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0004_remove_anime_episodes_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="video_url",
        ),
        migrations.AddField(
            model_name="episode",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="anime",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
