# Generated by Django 4.2.13 on 2024-08-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anime", "0005_remove_anime_genres_remove_anime_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="anime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by_favorite",
                to="anime.anime",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_anime",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorited_by_userprofile",
                        to="anime.anime",
                    ),
                ),
                (
                    "to_watch_anime",
                    models.ManyToManyField(
                        blank=True, related_name="to_watch_by", to="anime.anime"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watched_anime",
                    models.ManyToManyField(
                        blank=True, related_name="watched_by", to="anime.anime"
                    ),
                ),
            ],
        ),
    ]
