# Generated by Django 4.2.13 on 2024-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0006_alter_favorite_anime_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_anime",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="anime.anime"
            ),
        ),
    ]
