# Generated by Django 4.2.13 on 2024-08-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0008_anime_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="to_watch_anime",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_to_watch_anime",
            field=models.ManyToManyField(
                blank=True, related_name="planned_by", to="anime.anime"
            ),
        ),
    ]
